<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SRINIVAS-G2005" failures="1" tests="10" name="Test" time="33.029" errors="0" timestamp="2025-04-18T19:47:28 IST">
  <testcase classname="api.test.User_DDTests" name="testPostUser" time="5.897"/>
  <testcase classname="api.test.User_DDTests" name="testPostUser" time="1.741"/>
  <testcase classname="api.test.User_DDTests" name="testPostUser" time="2.892"/>
  <testcase classname="api.test.User_DDTests" name="testDeleteUserByName" time="2.133"/>
  <testcase classname="api.test.User_DDTests" name="testDeleteUserByName" time="1.842"/>
  <testcase classname="api.test.User_DDTests" name="testDeleteUserByName" time="2.354"/>
  <testcase classname="api.test.UserTests" name="testPostUser" time="3.479"/>
  <testcase classname="api.test.UserTests" name="testGetUserByName" time="2.61">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testGetUserByName(UserTests.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.test.UserTests" name="testUpdateUserByName" time="5.311"/>
  <testcase classname="api.test.UserTests" name="testDeleteUserByName" time="1.908"/>
</testsuite> <!-- Test -->
